import ethereumSvg from '../../../../../public/svg/ethereum.svg';
import polyGamingSvg from '../../../../../public/svg/poly-game.svg';
import polyClusterSvg from '../../../../../public/svg/poly-cluster.svg';
import wmaticWthSvg from '../../../../../public/svg/wmatic-wth.svg';
export const dataPoint = [
  {
    id: 1,
    icon: ethereumSvg,
    title: 'eth-core',
    price: 123.25,
    volume: 'cluster',
    priceLevel: 'join cluster',
    time: '12:53.15 AM',
  },
  {
    id: 2,
    icon: polyGamingSvg,
    title: 'poly gaming',
    price: 100123.25,
    volume: 'cluster',
    priceLevel: 'unstake cluster',
    time: '12:23.54 AM',
  },
  {
    id: 3,
    icon: ethereumSvg,
    title: 'eth-core',
    price: 1543.0,
    volume: 'cluster',
    priceLevel: 'stake cluster',
    time: '11:47.22 AM',
  },
  {
    id: 4,
    icon: polyClusterSvg,
    title: 'polycluster',
    price: 543.0,
    volume: 'cluster',
    priceLevel: 'leave cluster',
    time: '11:34.57 AM',
  },
  {
    id: 5,
    icon: wmaticWthSvg,
    title: 'wmatic/wth',
    price: 1124.47,
    volume: 'impulse',
    priceLevel: 'stake impulse',
    time: '11:47.22 AM',
  },
  {
    id: 6,
    icon: polyClusterSvg,
    title: 'poly cluster',
    price: 22.36,
    volume: 'cluster',
    priceLevel: 'claim rewards',
    time: '11:34.57 AM',
  },
  {
    id: 7,
    icon: wmaticWthSvg,
    title: 'wmatic/wth',
    price: 1124.47,
    volume: 'impulse',
    priceLevel: 'stake impulse',
    time: '11:47.22 AM',
  },
  {
    id: 8,
    icon: polyGamingSvg,
    title: 'poly gaming',
    price: 100123.25,
    volume: 'cluster',
    priceLevel: 'claim rewards',
    time: '12:23.54 AM',
  },
];